name: Markdown

on:
  # Run on all pushes which touch markdown files and on all pull requests.
  push:
    paths:
      - '**.md'
  pull_request:
  # Also run this workflow every Monday at 6:00 (to make sure the broken link check runs regularly).
  schedule:
    - cron: '0 6 * * 1'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    name: 'Lint Markdown'
    runs-on: ubuntu-latest

    # Don't run the cronjob in this workflow on forks.
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'PHPCSStandards')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # @link https://github.com/marketplace/actions/problem-matcher-for-markdownlint-cli
      - name: Enable showing issue in PRs
        uses: xt0rted/markdownlint-problem-matcher@v3

      # @link https://github.com/marketplace/actions/markdownlint-cli2-action
      - name: Check markdown with CLI2
        uses: DavidAnson/markdownlint-cli2-action@v15
